# Generated by Django 4.2.30 on 2026-08-27 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Código de Departamento')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'catalogo_department',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Código de Provincia')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='catalogo.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'catalogo_province',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='UBIGEO')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometría')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='catalogo.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'catalogo_district',
                'ordering': ['ubigeo'],
            },
        ),
    ]
