# Generated by Django 4.2.30 on 2026-08-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_department_geometry_province_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=20, unique=True, verbose_name='Código Único')),
                ('name', models.TextField(verbose_name='Nombre de inversión')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo actualizado')),
                ('executed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Devengado acumulado')),
                ('pim', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PIM')),
                ('prog_year_1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Año 1')),
                ('prog_year_2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Año 2')),
                ('prog_year_3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Año 3')),
                ('prog_year_4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Año 4')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('physical_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avance Físico %')),
                ('general_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avance General %')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='Fecha Reporte Avance')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='catalogo.district', verbose_name='Distrito (UBIGEO)')),
            ],
            options={
                'verbose_name': 'Proyecto de Inversión',
                'verbose_name_plural': 'Proyectos de Inversión',
                'db_table': 'inversiones_project',
            },
        ),
    ]
