# Generated by Django 4.2.30 on 2026-08-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0002_project_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Habitantes beneficiarios'),
        ),
        migrations.AddField(
            model_name='project',
            name='entity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='project',
            name='monto_viable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto viable'),
        ),
        migrations.AddField(
            model_name='project',
            name='snip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código SNIP'),
        ),
        migrations.AddField(
            model_name='project',
            name='typology',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipología'),
        ),
    ]
