# Generated by Django 4.2.30 on 2026-08-27 19:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_department_geometry_province_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nombre')),
                ('acronym', models.CharField(blank=True, max_length=80, verbose_name='sigla')),
                ('provider_type', models.CharField(blank=True, max_length=80, verbose_name='tipo')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='datos de origen')),
            ],
            options={
                'verbose_name': 'prestador',
                'verbose_name_plural': 'prestadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='identificador externo')),
                ('system_name', models.CharField(blank=True, max_length=250, verbose_name='sistema')),
                ('locality', models.CharField(blank=True, max_length=250, verbose_name='localidad')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='ámbito de prestación')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='datos de origen')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_areas', to='catalogo.department')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_areas', to='capas.provider')),
            ],
            options={
                'verbose_name': 'ámbito de prestación',
                'verbose_name_plural': 'ámbitos de prestación',
                'ordering': ['department__name', 'provider__name', 'system_name'],
                'indexes': [models.Index(fields=['department', 'provider'], name='capas_servi_departm_bf73e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContinuityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='nombre')),
                ('group', models.CharField(blank=True, max_length=150, verbose_name='grupo')),
                ('province_name', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('district_name', models.CharField(blank=True, max_length=100, verbose_name='distrito')),
                ('sector', models.CharField(blank=True, max_length=150, verbose_name='sector')),
                ('locality', models.CharField(blank=True, max_length=150, verbose_name='localidad')),
                ('day', models.CharField(blank=True, max_length=50, verbose_name='día')),
                ('hour', models.CharField(blank=True, max_length=50, verbose_name='hora')),
                ('promised_service', models.CharField(blank=True, max_length=150, verbose_name='servicio prometido')),
                ('external_key', models.CharField(blank=True, max_length=150, verbose_name='clave externa')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='ubicación')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='datos de origen')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='continuity_points', to='catalogo.department')),
            ],
            options={
                'verbose_name': 'punto de continuidad',
                'verbose_name_plural': 'puntos de continuidad',
                'ordering': ['department__name', 'district_name', 'name'],
                'indexes': [models.Index(fields=['department', 'district_name'], name='capas_conti_departm_9304d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContinuityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='VORONOI', max_length=100, verbose_name='método')),
                ('average_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='horas promedio')),
                ('relative_value', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='valor relativo')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='área')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='datos de origen')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='continuity_areas', to='catalogo.department')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuity_areas', to='capas.provider')),
            ],
            options={
                'verbose_name': 'área de continuidad',
                'verbose_name_plural': 'áreas de continuidad',
                'ordering': ['department__name', 'method'],
                'indexes': [models.Index(fields=['department', 'method'], name='capas_conti_departm_d52731_idx')],
            },
        ),
    ]
