# Generated by Django 4.2.30 on 2026-08-28 15:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterStressBasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin_id', models.CharField(db_index=True, max_length=64, verbose_name='código de cuenca')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='nombre de cuenca')),
                ('demand_val', models.FloatField(blank=True, null=True, verbose_name='demanda 2050 (m3/año)')),
                ('supply_val', models.FloatField(blank=True, null=True, verbose_name='oferta 2050 (m3/año)')),
                ('demand_cls', models.IntegerField(blank=True, null=True, verbose_name='cuartil demanda (1-4)')),
                ('supply_cls', models.IntegerField(blank=True, null=True, verbose_name='cuartil oferta (1-4)')),
                ('bivar_cls', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='clase bivariada (1-16)')),
                ('stress_category', models.CharField(blank=True, max_length=100, verbose_name='categoría de riesgo')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geometría de cuenca')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='datos de origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cuenca de estrés hídrico',
                'verbose_name_plural': 'cuencas de estrés hídrico',
                'ordering': ['bivar_cls', 'basin_id'],
                'indexes': [models.Index(fields=['bivar_cls'], name='capas_water_bivar_c_81010b_idx')],
            },
        ),
    ]
