# Generated by Django 4.2.30 on 2026-08-28 16:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_department_geometry_province_geometry'),
        ('capas', '0002_waterstressbasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPoblado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ccpp', models.CharField(db_index=True, max_length=20, verbose_name='código CCPP')),
                ('name', models.CharField(max_length=200, verbose_name='nombre centro poblado')),
                ('province_name', models.CharField(blank=True, max_length=150, verbose_name='provincia')),
                ('district_name', models.CharField(blank=True, max_length=150, verbose_name='distrito')),
                ('district_ubigeo', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='UBIGEO distrito')),
                ('pob_total', models.IntegerField(default=0, verbose_name='población total')),
                ('num_viv', models.IntegerField(default=0, verbose_name='total viviendas')),
                ('pvs_agua_red', models.FloatField(blank=True, null=True, verbose_name='% agua red pública')),
                ('pvs_sin_saneamiento', models.FloatField(blank=True, null=True, verbose_name='% sin saneamiento')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='punto centroide')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='polígono de centro poblado')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='datos censales completos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_poblados', to='catalogo.department')),
            ],
            options={
                'verbose_name': 'Centro Poblado',
                'verbose_name_plural': 'Centros Poblados',
                'ordering': ['department__name', 'district_name', '-pob_total'],
                'indexes': [models.Index(fields=['department', 'district_ubigeo'], name='capas_centr_departm_bb1ba3_idx')],
            },
        ),
    ]
