# Generated by Django 4.2.30 on 2026-08-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0003_centropoblado'),
    ]

    operations = [
        migrations.AddField(
            model_name='centropoblado',
            name='total_executed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='monto invertido'),
        ),
        migrations.AddField(
            model_name='centropoblado',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='monto planificado'),
        ),
        migrations.AddField(
            model_name='centropoblado',
            name='total_projects',
            field=models.IntegerField(default=0, verbose_name='total proyectos'),
        ),
    ]
