# Generated by Django 4.2.30 on 2026-08-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
                ('source_type', models.CharField(choices=[('CSV', 'CSV'), ('SHP', 'Shapefile'), ('GPKG', 'GeoPackage'), ('XLSX', 'Excel'), ('GEOJSON', 'GeoJSON')], max_length=20, verbose_name='tipo')),
                ('relative_path', models.CharField(max_length=500, verbose_name='ruta relativa')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='versión')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado')),
            ],
            options={
                'verbose_name': 'fuente de datos',
                'verbose_name_plural': 'fuentes de datos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'En ejecución'), ('SUCCESS', 'Correcta'), ('FAILED', 'Fallida')], default='RUNNING', max_length=20, verbose_name='estado')),
                ('rows_read', models.PositiveIntegerField(default=0, verbose_name='filas leídas')),
                ('rows_created', models.PositiveIntegerField(default=0, verbose_name='filas creadas')),
                ('rows_updated', models.PositiveIntegerField(default=0, verbose_name='filas actualizadas')),
                ('rows_rejected', models.PositiveIntegerField(default=0, verbose_name='filas rechazadas')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='errores')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='ingestion.datasource')),
            ],
            options={
                'verbose_name': 'ejecución de importación',
                'verbose_name_plural': 'ejecuciones de importación',
                'ordering': ['-started_at'],
            },
        ),
    ]
